import type { Metadata } from "next";
import { DM_Sans, Noto_Sans_Mono } from "next/font/google";
import "./globals.css";

const notoSansMono = Noto_Sans_Mono({
  subsets: ["latin"],
  weight: ["500"],
  variable: "--noto-sans-mono",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["600", "700"],
  variable: "--dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSansMono.variable} ${dmSans.variable} bg-[#FFFEF2]`}
      >
        {children}
      </body>
    </html>
  );
}
